name: 同步dcloudio-uni-app仓库
on:
  schedule:
    - cron: '36 6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-dcloudio-uni-app
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync dcloudio-uni-app
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/dcloudio/uni-app.git"
          source_branch: "dev"
          destination_branch: "uni-app"
          github_token: ${{ secrets.PAT }}
