name: 同步mshufflewzc/faker2仓库
on:
  schedule:
    - cron: '25 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-shufflewzc-faker2
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync shufflewzc-faker2
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/shufflewzc/faker2.git"
          source_branch: "main"
          destination_branch: "faker2"
          github_token: ${{ secrets.PAT }}
