name: 同步mirai仓库
on:
  schedule:
    - cron: '5 * 1 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-mamoe-mirai
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync mamoe-mirai
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/mamoe/mirai.git"
          source_branch: "dev"
          destination_branch: "mirai"
          github_token: ${{ secrets.PAT }}
